-- database: :memory:
-- Tables
create table if not exists profiles (
  id uuid primary key references auth.users on delete cascade,
  email text unique,
  display_name text,
  created_at timestamptz default now()
);

create table if not exists channels (
  id bigint generated by default as identity primary key,
  name text not null,
  created_by uuid references profiles(id) on delete set null,
  is_dm boolean default false,
  dm_pair text unique,
  created_at timestamptz default now()
);

create table if not exists channel_members (
  channel_id bigint references channels(id) on delete cascade,
  user_id uuid references profiles(id) on delete cascade,
  created_at timestamptz default now(),
  primary key (channel_id, user_id)
);

create table if not exists messages (
  id bigint generated by default as identity primary key,
  channel_id bigint references channels(id) on delete cascade,
  user_id uuid references profiles(id) on delete set null,
  body text not null,
  created_at timestamptz default now()
);

create table if not exists friendships (
  user_id uuid references profiles(id) on delete cascade,
  friend_id uuid references profiles(id) on delete cascade,
  status text default 'accepted',
  created_at timestamptz default now(),
  primary key (user_id, friend_id)
);

-- Enable RLS
alter table profiles enable row level security;
alter table channels enable row level security;
alter table channel_members enable row level security;
alter table messages enable row level security;
alter table friendships enable row level security;

-- Profiles: allow authenticated to read (for friends + display names)
create policy "profiles_select_authenticated" on profiles
  for select using (auth.uid() is not null);
create policy "profiles_insert_own" on profiles
  for insert with check (id = auth.uid());
create policy "profiles_update_own" on profiles
  for update using (id = auth.uid());

-- Channels: any authenticated can read/create
create policy "channels_select_all" on channels
  for select using (auth.uid() is not null);
create policy "channels_insert_authenticated" on channels
  for insert with check (auth.uid() is not null);

-- Channel members:
-- allow users to join themselves, and allow channel creators to add members
create policy "channel_members_select_self" on channel_members
  for select using (user_id = auth.uid());
create policy "channel_members_insert_self_or_owner" on channel_members
  for insert with check (
    user_id = auth.uid()
    or exists (
      select 1 from channels c
      where c.id = channel_id and c.created_by = auth.uid()
    )
  );

-- Messages: only members can read/send
create policy "messages_select_members" on messages
  for select using (
    exists (
      select 1 from channel_members cm
      where cm.channel_id = messages.channel_id and cm.user_id = auth.uid()
    )
  );
create policy "messages_insert_members" on messages
  for insert with check (
    user_id = auth.uid()
    and exists (
      select 1 from channel_members cm
      where cm.channel_id = messages.channel_id and cm.user_id = auth.uid()
    )
  );

-- Friendships: manage your own list
create policy "friendships_select_own" on friendships
  for select using (user_id = auth.uid());
create policy "friendships_insert_own" on friendships
  for insert with check (user_id = auth.uid());
